
create table scn.somos_member_insights_claim_status (
  id_claim_status integer,
  claim_id INTEGER,
  claim_status varchar(500),
  file_status varchar(50),
  file_last_sent TIMESTAMP,
  date_response_processed TIMESTAMP,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);
  
create table scn.somos_member_insights_claims (
  id_claims integer,
  claim_id INTEGER,
  referral_id INTEGER,
  form_submission_id INTEGER,
  program_numeric_id bigint,
  seeker_profile_id INTEGER,
  seeker_id INTEGER,
  navigator_user_id INTEGER,
  member_firstname varchar(100),
  member_lastname varchar(100),
  member_middlename varchar(100),
  member_dob date,
  member_phone varchar(20),
  member_address varchar(255),
  member_city varchar(100),
  member_state varchar(2),
  member_zip INTEGER,
  member_medicaid_id varchar(100),
  payor_id varchar(20),
  payor_name varchar(100),
  member_policy_number varchar(50),
  member_plan varchar(100),
  member_PID varchar(100),
  rendering_provider varchar(255),
  rendering_provider_address varchar(255),
  rendering_provider_city varchar(100),
  rendering_provider_state varchar(2),
  rendering_provider_phone varchar(20),
  rendering_provider_tin varchar(45),
  rendering_provider_npi varchar(45),
  rate_code varchar(100),
  diagnosis_codes varchar(255),
  procedure_code varchar(50),
  procedure_modifier_codes varchar(10),
  service_start_date TIMESTAMP,
  service_end_date TIMESTAMP,
  service_name varchar(1000),
  service_unit_count INTEGER,
  service_unit_cost double precision,
  total_cost double precision,
  claim_created_at TIMESTAMP,
  claim_updated_at TIMESTAMP,
  extra varchar(max)
);  
create table scn.somos_member_insights_encounters (
  id_encounters integer,
  encounters_id INTEGER,
  provider_id INTEGER,
  subdomain varchar(100),
  navigator_user_id INTEGER,
  seeker_profile_id INTEGER,
  seeker_id INTEGER,
  activity_id bigint,
  activity_type varchar(100),
  encounter_type varchar(100),
  encounter_status varchar(100),
  encounter_entry_date TIMESTAMP,
  opened_at TIMESTAMP,
  closed_at TIMESTAMP,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);   
create table scn.somos_member_insights_encounters_metadata (
  id_encounter_metadata integer,
  encounters_id INTEGER,
  metadata_key VARCHAR(MAX),
  text_value VARCHAR(MAX),
  bigint,_value bigint,
  boolean_value smallint,
  encounter_metadata_date TIMESTAMP,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);   
create table scn.somos_member_insights_flexible_referral_fields (
  id_flexible_referral_fields integer,
  referral_id INTEGER,
  choice VARCHAR(MAX),
  referral_field_label VARCHAR(MAX),
  referral_field_description VARCHAR(MAX),
  updated_by_user_id INTEGER,
  flexible_referral_field_id INTEGER,
  subdomain varchar(100),
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);  
create table scn.somos_member_insights_forms (
  id_forms integer,
  form_submission_id INTEGER,
  form_version_id INTEGER,
  form_name varchar(255),
  submitter_user_id INTEGER,
  seeker_id INTEGER,
  seeker_profile_id INTEGER,
  referral_id INTEGER,
  self_serve varchar(100),
  kiosk_only varchar(10),
  question varchar(1000),
  question_unique_id INTEGER,
  question_submission_id INTEGER,
  answer_item_labels VARCHAR(MAX),
  answer_item_ids VARCHAR(MAX),
  answer_item_scores VARCHAR(MAX),
  question_type varchar(50),
  answer VARCHAR(MAX),
  answer_score INTEGER,
  kiosk varchar(100),
  subdomain varchar(45),
  required_question smallint,
  domain_ids VARCHAR(MAX),
  domains VARCHAR(MAX),
  postal varchar(5),
  language varchar(100),
  form_type varchar(100),
  started_at TIMESTAMP,
  created_at TIMESTAMP,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);  
create table scn.somos_member_insights_goals (
  id_goals integer,
  goal_id INTEGER,
  author_user_id INTEGER,
  seeker_id INTEGER,
  seeker_profile_id INTEGER,
  goal_description varchar(1500),
  goal_closed smallint,
  goal_created_at TIMESTAMP,
  goal_updated_at TIMESTAMP,
  goal_form_submission_id INTEGER,
  goal_status varchar(250),
  category varchar(100),
  seeker_notes_id INTEGER,
  goal_group_key varchar(255),
  goal_autoshared smallint,
  goal_group_created_at TIMESTAMP,
  goal_note VARCHAR(MAX),
  subdomain varchar(45),
  entry_date TIMESTAMP,
  update_date TIMESTAMP,
  etl_increment_hash varchar(255)
);  
create table scn.somos_member_insights_notes (
  id_notes integer,
  note_id INTEGER,
  seeker_id INTEGER,
  author_user_id INTEGER,
  note_text varchar(10000),
  note_type varchar(50),
  note_type_id bigint,
  subdomain varchar(100),
  note_created_at timestamp,
  note_updated_at timestamp,
  is_deleted smallint,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);   
create table scn.somos_member_insights_programs (
  id_programs integer,
  program_numeric_id bigint,
  program_name varchar(500),
  provider_numeric_id bigint,
  provider_name varchar(500),
  categories varchar(100),
  service_tags VARCHAR(MAX),
  program_published_status varchar(15),
  nonlistable_status varchar(11),
  program_connect_method varchar(25),
  coverage_grain varchar(100),
  coverage_area varchar(255),
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);

create table scn.somos_member_insights_referrals (
  id_referrals integer,
  referral_key varchar(100),
  referral_numeric_id bigint,
  referral_id INTEGER,
  seeker_id INTEGER,
  seeker_profile_id INTEGER,
  sender_user_id INTEGER,
  form_submission_id INTEGER,
  referral_date TIMESTAMP,
  referral_connection_type varchar(100),
  referral_status varchar(100),
  status_last_updated TIMESTAMP,
  referral_acknowledge_date TIMESTAMP,
  contact_method varchar(25),
  sent smallint,
  subdomain varchar(100),
  postal varchar(5),
  postal_county_state varchar(1000),
  consent smallint,
  program_numeric_id bigint,
  goal_id INTEGER,
  referral_comment varchar(1000),
  eff_start_date TIMESTAMP,
  eff_end_date TIMESTAMP,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);  
create table scn.somos_member_insights_sdoh_code_sets (
  id_code_sets integer,
  entity_type varchar(50),
  entity_id bigint,
  code varchar(255),
  code_set varchar(50),
  data_OID varchar(255),
  description VARCHAR(MAX),
  subdomain varchar(50),
  code_create_date TIMESTAMP,
  code_update_date TIMESTAMP,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);   
create table scn.somos_member_insights_seeker_profile_custom_values (
  id_user_profile_custom_values integer,
  field_value_id INTEGER,
  seeker_profile_id INTEGER,
  seeker_id INTEGER,
  subdomain varchar(45),
  field_name varchar(255),
  value VARCHAR(MAX),
  is_identifier smallint,
  value_created_at TIMESTAMP,
  value_updated_at TIMESTAMP,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);  
create table scn.somos_member_insights_seeker_profiles (
  id_customer_seeker_profiles integer,
  seeker_profile_id INTEGER,
  seeker_id INTEGER,
  email varchar(255),
  username varchar(255),
  phone_number varchar(10),
  first_name varchar(64),
  last_name varchar(64),
  is_archived smallint,
  follow_up smallint,
  profile_assignee_user_id INTEGER,
  accepted_terms_date TIMESTAMP,
  subdomain varchar(45),
  human_key varchar(100),
  consent smallint,
  is_current smallint,
  seeker_profile_created_at TIMESTAMP,
  seeker_profile_updated_at timestamp,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);   
create table scn.somos_member_insights_user_activity (
  id_user_activity integer,
  user_id INTEGER,
  Source varchar(8),
  activity_type varchar(45),
  activity_data VARCHAR(MAX),
  category varchar(45),
  search_result_count INTEGER,
  related_object varchar(500),
  related_object_type varchar(100),
  activity_entry_date TIMESTAMP,
  subdomain varchar(45),
  followed_url varchar(250),
  postal varchar(5),
  cookie varchar(100),
  user_agent varchar(250),
  device_type varchar(25),
  screen_size real,
  engagement VARCHAR(MAX),
  program_numeric_id bigint,
  link_url varchar(250),
  ip_address varchar(50),
  ip_organization varchar(120),
  id_all_activity INTEGER,
  session_id varchar(55),
  session_click_sequence INTEGER,
  session_begin_time TIMESTAMP,
  session_end_time TIMESTAMP,
  session_time_in_minutes INTEGER,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);  
create table scn.somos_member_insights_user_external_identifiers (
  id_user_external_identifiers integer,
  user_id INTEGER,
  external_name varchar(100),
  external_identifier varchar(100),
  subdomain varchar(2048),
  referral_id INTEGER,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);   
create table scn.somos_member_insights_worker_profiles (
  id_worker_profiles integer,
  user_id INTEGER,
  first_name varchar(50),
  last_name varchar(50),
  registered_email varchar(255),
  phone_number varchar(50),
  department varchar(250),
  role_function varchar(150),
  worker_type varchar(45),
  status varchar(10),
  inactive_date TIMESTAMP,
  worker_last_activity_date TIMESTAMP,
  subdomain varchar(45),
  worker_organization_type varchar(10),
  worker_organization_name varchar(500),
  worker_creation_date TIMESTAMP,
  worker_update_date TIMESTAMP,
  entry_date TIMESTAMP,
  update_date TIMESTAMP
);   
