create
temporary table stg_encounter (Appointment_Date varchar(255), Admission_Date varchar(255), Discharge_Date varchar(255), Appointment_Start_Time varchar(255), Is_Sunoh_ai varchar(255), Is_Televisit varchar(255), Call_Start_Time varchar(255), Call_End_Time varchar(255), Call_Duration varchar(255), Encounter_ID varchar(255), Visit_Type varchar(255), Visit_SubType varchar(255), Visit_Status varchar(255), Case_Label varchar(255), Appointment_Created_By_User varchar(255), Visit_Count varchar(255), Patient_Count varchar(255), Patient_Name varchar(255), Patient_First_Name varchar(255), Patient_Last_Name varchar(255), Patient_Middle_Initial varchar(255), Patient_Acct_No varchar(255), Patient_DOB varchar(255), Patient_Gender varchar(255), Patient_Address_Line_1 varchar(255), Patient_Address_Line_2 varchar(255), Patient_City varchar(255), Patient_State varchar(255), Patient_ZIP_Code varchar(255), Patient_Full_Address varchar(255), Patient_Race varchar(255), Patient_Ethnicity varchar(255), Patient_Language varchar(255), Patient_Home_Phone varchar(255), Patient_Cell_Phone varchar(255), Patient_Work_Phone varchar(255), Patient_Email varchar(255), Patient_Status varchar(255), Dont_Send_Statements varchar(255), Patient_Deceased varchar(255), Patient_Age_Group varchar(255), Birth_Sex varchar(255), Gender_Identity_Name varchar(255), Gender_Identity_SNOMED_Code varchar(255), Sexual_Orientation_Name varchar(255), Sexual_Orientation_SNOMED_Code varchar(255), Appointment_Facility_Name varchar(255), Appointment_Facility_POS varchar(255), Appointment_Facility_Group_Name varchar(255), Department_Name varchar(255), Practice_Name varchar(255), Appointment_Provider_Name varchar(255), Appointment_Provider_NPI varchar(255), Appointment_Referring_Provider_Name varchar(255), Appointment_Referring_Provider_NPI varchar(255), Resource_Provider_Name varchar(255), Resource_Provider_NPI varchar(255), Demographics_PCP_Name varchar(255), Demographics_PCP_NPI varchar(255), Demographics_Referring_Provider_Name varchar(255), Demographics_Referring_Provider_NPI varchar(255), Demographics_Rendering_Provider_Name varchar(255), Demographics_Rendering_Provider_NPI varchar(255), Primary_Insurance_Name varchar(255), Primary_Insurance_Subscriber_No varchar(255), Secondary_Insurance_Name varchar(255), Secondary_Insurance_Subscriber_No varchar(255), Tertiary_Insurance_Name varchar(255), Tertiary_Insurance_Subscriber_No varchar(255), Sliding_Fee_Schedule varchar(255), Appointment_Employer varchar(255));

copy stg_encounter
from 's3://sftp_test/ecw_automation/appointments/FILENAME' iam_role 'arn:aws:iam::042108671686:role/myRedshiftRole' region 'us-east-1'
delimiter '|' blanksasnull IGNOREHEADER 1 format as csv;


insert into appointments.ecw_appointments (Appointment_Date, Admission_Date, Discharge_Date, Appointment_Start_Time, Is_Sunoh_ai, Is_Televisit, Call_Start_Time, Call_End_Time, Call_Duration, Encounter_ID, Visit_Type, Visit_SubType, Visit_Status, Case_Label, Appointment_Created_By_User, Visit_Count, Patient_Count, Patient_Name, Patient_First_Name, Patient_Last_Name, Patient_Middle_Initial, Patient_Acct_No, Patient_DOB, Patient_Gender, Patient_Address_Line_1, Patient_Address_Line_2, Patient_City, Patient_State, Patient_ZIP_Code, Patient_Full_Address, Patient_Race, Patient_Ethnicity, Patient_Language, Patient_Home_Phone, Patient_Cell_Phone, Patient_Work_Phone, Patient_Email, Patient_Status, Dont_Send_Statements, Patient_Deceased, Patient_Age_Group, Birth_Sex, Gender_Identity_Name, Gender_Identity_SNOMED_Code, Sexual_Orientation_Name, Sexual_Orientation_SNOMED_Code, Appointment_Facility_Name, Appointment_Facility_POS, Appointment_Facility_Group_Name, Department_Name, Practice_Name, Appointment_Provider_Name, Appointment_Provider_NPI, Appointment_Referring_Provider_Name, Appointment_Referring_Provider_NPI, Resource_Provider_Name, Resource_Provider_NPI, Demographics_PCP_Name, Demographics_PCP_NPI, Demographics_Referring_Provider_Name, Demographics_Referring_Provider_NPI, Demographics_Rendering_Provider_Name, Demographics_Rendering_Provider_NPI, Primary_Insurance_Name, Primary_Insurance_Subscriber_No, Secondary_Insurance_Name, Secondary_Insurance_Subscriber_No, Tertiary_Insurance_Name, Tertiary_Insurance_Subscriber_No, Sliding_Fee_Schedule, Appointment_Employer, file_name, added_tz, modified_tz)
select Appointment_Date,
       Admission_Date,
       Discharge_Date,
       Appointment_Start_Time,
       Is_Sunoh_ai,
       Is_Televisit,
       Call_Start_Time,
       Call_End_Time,
       Call_Duration,
       Encounter_ID,
       Visit_Type,
       Visit_SubType,
       Visit_Status,
       Case_Label,
       Appointment_Created_By_User,
       Visit_Count,
       Patient_Count,
       Patient_Name,
       Patient_First_Name,
       Patient_Last_Name,
       Patient_Middle_Initial,
       Patient_Acct_No,
       Patient_DOB,
       Patient_Gender,
       Patient_Address_Line_1,
       Patient_Address_Line_2,
       Patient_City,
       Patient_State,
       Patient_ZIP_Code,
       Patient_Full_Address,
       Patient_Race,
       Patient_Ethnicity,
       Patient_Language,
       Patient_Home_Phone,
       Patient_Cell_Phone,
       Patient_Work_Phone,
       Patient_Email,
       Patient_Status,
       Dont_Send_Statements,
       Patient_Deceased,
       Patient_Age_Group,
       Birth_Sex,
       Gender_Identity_Name,
       Gender_Identity_SNOMED_Code,
       Sexual_Orientation_Name,
       Sexual_Orientation_SNOMED_Code,
       Appointment_Facility_Name,
       Appointment_Facility_POS,
       Appointment_Facility_Group_Name,
       Department_Name,
       Practice_Name,
       Appointment_Provider_Name,
       Appointment_Provider_NPI,
       Appointment_Referring_Provider_Name,
       Appointment_Referring_Provider_NPI,
       Resource_Provider_Name,
       Resource_Provider_NPI,
       Demographics_PCP_Name,
       Demographics_PCP_NPI,
       Demographics_Referring_Provider_Name,
       Demographics_Referring_Provider_NPI,
       Demographics_Rendering_Provider_Name,
       Demographics_Rendering_Provider_NPI,
       Primary_Insurance_Name,
       Primary_Insurance_Subscriber_No,
       Secondary_Insurance_Name,
       Secondary_Insurance_Subscriber_No,
       Tertiary_Insurance_Name,
       Tertiary_Insurance_Subscriber_No,
       Sliding_Fee_Schedule,
       Appointment_Employer,
       'FILENAME' as file_name,
       trunc(getdate()) as added_tz,
       NULL as modified_tz
from stg_encounter;